<?php
// This script and data application were generated by AppGini 5.76
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Cotrol_Acad.php");
	include("$currDir/Cotrol_Acad_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Cotrol_Acad');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Cotrol_Acad";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Cotrol_Acad`.`id`" => "id",
		"`Cotrol_Acad`.`Codigo`" => "Codigo",
		"`Cotrol_Acad`.`Seccion`" => "Seccion",
		"`Cotrol_Acad`.`Nombre`" => "Nombre",
		"`Cotrol_Acad`.`Aula`" => "Aula",
		"`Cotrol_Acad`.`Dia`" => "Dia",
		"`Cotrol_Acad`.`Hora_Inicio`" => "Hora_Inicio",
		"`Cotrol_Acad`.`Hora_Final`" => "Hora_Final",
		"`Cotrol_Acad`.`Fecha_inicion`" => "Fecha_inicion",
		"`Cotrol_Acad`.`Facilitador`" => "Facilitador",
		"`Cotrol_Acad`.`mapa`" => "mapa",
		"`Cotrol_Acad`.`mapa_link`" => "mapa_link"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Cotrol_Acad`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`Cotrol_Acad`.`Aula`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Cotrol_Acad`.`id`" => "id",
		"`Cotrol_Acad`.`Codigo`" => "Codigo",
		"`Cotrol_Acad`.`Seccion`" => "Seccion",
		"`Cotrol_Acad`.`Nombre`" => "Nombre",
		"`Cotrol_Acad`.`Aula`" => "Aula",
		"`Cotrol_Acad`.`Dia`" => "Dia",
		"`Cotrol_Acad`.`Hora_Inicio`" => "Hora_Inicio",
		"`Cotrol_Acad`.`Hora_Final`" => "Hora_Final",
		"`Cotrol_Acad`.`Fecha_inicion`" => "Fecha_inicion",
		"`Cotrol_Acad`.`Facilitador`" => "Facilitador",
		"`Cotrol_Acad`.`mapa`" => "mapa",
		"`Cotrol_Acad`.`mapa_link`" => "mapa_link"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Cotrol_Acad`.`id`" => "ID",
		"`Cotrol_Acad`.`Codigo`" => "C&#243;digo",
		"`Cotrol_Acad`.`Seccion`" => "Secci&#243;n",
		"`Cotrol_Acad`.`Nombre`" => "Nombre",
		"`Cotrol_Acad`.`Aula`" => "Aula",
		"`Cotrol_Acad`.`Dia`" => "D&#237;a",
		"`Cotrol_Acad`.`Hora_Inicio`" => "Hora Inicio",
		"`Cotrol_Acad`.`Hora_Final`" => "Hora Final",
		"`Cotrol_Acad`.`Fecha_inicion`" => "Fecha inicion",
		"`Cotrol_Acad`.`Facilitador`" => "Facilitador",
		"`Cotrol_Acad`.`mapa`" => "Mapa",
		"`Cotrol_Acad`.`mapa_link`" => "Mapa link"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Cotrol_Acad`.`id`" => "id",
		"`Cotrol_Acad`.`Codigo`" => "Codigo",
		"`Cotrol_Acad`.`Seccion`" => "Seccion",
		"`Cotrol_Acad`.`Nombre`" => "Nombre",
		"`Cotrol_Acad`.`Aula`" => "Aula",
		"`Cotrol_Acad`.`Dia`" => "Dia",
		"`Cotrol_Acad`.`Hora_Inicio`" => "Hora_Inicio",
		"`Cotrol_Acad`.`Hora_Final`" => "Hora_Final",
		"`Cotrol_Acad`.`Fecha_inicion`" => "Fecha_inicion",
		"`Cotrol_Acad`.`Facilitador`" => "Facilitador",
		"`Cotrol_Acad`.`mapa`" => "mapa",
		"`Cotrol_Acad`.`mapa_link`" => "mapa_link"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Cotrol_Acad` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Cotrol_Acad_view.php";
	$x->RedirectAfterInsert = "Cotrol_Acad_view.php?SelectedID=#ID#";
	$x->TableTitle = "Control Acad&#233;mico";
	$x->TableIcon = "resources/table_icons/application_view_detail.png";
	$x->PrimaryKey = "`Cotrol_Acad`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("C&#243;digo", "Secci&#243;n", "Nombre", "Aula", "D&#237;a", "Hora Inicio", "Hora Final", "Fecha inicion", "Facilitador", "Mapa", "Mapa link");
	$x->ColFieldName = array('Codigo', 'Seccion', 'Nombre', 'Aula', 'Dia', 'Hora_Inicio', 'Hora_Final', 'Fecha_inicion', 'Facilitador', 'mapa', 'mapa_link');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Cotrol_Acad_templateTV.html';
	$x->SelectedTemplate = 'templates/Cotrol_Acad_templateTVS.html';
	$x->TemplateDV = 'templates/Cotrol_Acad_templateDV.html';
	$x->TemplateDVP = 'templates/Cotrol_Acad_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Cotrol_Acad`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Cotrol_Acad' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Cotrol_Acad`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Cotrol_Acad' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Cotrol_Acad`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Cotrol_Acad_init
	$render=TRUE;
	if(function_exists('Cotrol_Acad_init')){
		$args=array();
		$render=Cotrol_Acad_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Cotrol_Acad_header
	$headerCode='';
	if(function_exists('Cotrol_Acad_header')){
		$args=array();
		$headerCode=Cotrol_Acad_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Cotrol_Acad_footer
	$footerCode='';
	if(function_exists('Cotrol_Acad_footer')){
		$args=array();
		$footerCode=Cotrol_Acad_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>