<?php

// Data functions (insert, update, delete, form) for table Cotrol_Acad

// This script and data application were generated by AppGini 5.76
// Download AppGini for free from https://bigprof.com/appgini/download/

function Cotrol_Acad_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('Cotrol_Acad');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Codigo'] = makeSafe($_REQUEST['Codigo']);
		if($data['Codigo'] == empty_lookup_value){ $data['Codigo'] = ''; }
	$data['Seccion'] = makeSafe($_REQUEST['Seccion']);
		if($data['Seccion'] == empty_lookup_value){ $data['Seccion'] = ''; }
	$data['Nombre'] = makeSafe($_REQUEST['Nombre']);
		if($data['Nombre'] == empty_lookup_value){ $data['Nombre'] = ''; }
	$data['Aula'] = makeSafe($_REQUEST['Aula']);
		if($data['Aula'] == empty_lookup_value){ $data['Aula'] = ''; }
	$data['Dia'] = makeSafe($_REQUEST['Dia']);
		if($data['Dia'] == empty_lookup_value){ $data['Dia'] = ''; }
	$data['Hora_Inicio'] = makeSafe($_REQUEST['Hora_Inicio']);
		if($data['Hora_Inicio'] == empty_lookup_value){ $data['Hora_Inicio'] = ''; }
	$data['Hora_Final'] = makeSafe($_REQUEST['Hora_Final']);
		if($data['Hora_Final'] == empty_lookup_value){ $data['Hora_Final'] = ''; }
	$data['Fecha_inicion'] = makeSafe($_REQUEST['Fecha_inicion']);
		if($data['Fecha_inicion'] == empty_lookup_value){ $data['Fecha_inicion'] = ''; }
	$data['Facilitador'] = makeSafe($_REQUEST['Facilitador']);
		if($data['Facilitador'] == empty_lookup_value){ $data['Facilitador'] = ''; }
	$data['mapa'] = makeSafe($_REQUEST['mapa']);
		if($data['mapa'] == empty_lookup_value){ $data['mapa'] = ''; }
	$data['mapa_link'] = makeSafe($_REQUEST['mapa_link']);
		if($data['mapa_link'] == empty_lookup_value){ $data['mapa_link'] = ''; }

	// hook: Cotrol_Acad_before_insert
	if(function_exists('Cotrol_Acad_before_insert')){
		$args=array();
		if(!Cotrol_Acad_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `Cotrol_Acad` set       `Codigo`=' . (($data['Codigo'] !== '' && $data['Codigo'] !== NULL) ? "'{$data['Codigo']}'" : 'NULL') . ', `Seccion`=' . (($data['Seccion'] !== '' && $data['Seccion'] !== NULL) ? "'{$data['Seccion']}'" : 'NULL') . ', `Nombre`=' . (($data['Nombre'] !== '' && $data['Nombre'] !== NULL) ? "'{$data['Nombre']}'" : 'NULL') . ', `Aula`=' . (($data['Aula'] !== '' && $data['Aula'] !== NULL) ? "'{$data['Aula']}'" : 'NULL') . ', `Dia`=' . (($data['Dia'] !== '' && $data['Dia'] !== NULL) ? "'{$data['Dia']}'" : 'NULL') . ', `Hora_Inicio`=' . (($data['Hora_Inicio'] !== '' && $data['Hora_Inicio'] !== NULL) ? "'{$data['Hora_Inicio']}'" : 'NULL') . ', `Hora_Final`=' . (($data['Hora_Final'] !== '' && $data['Hora_Final'] !== NULL) ? "'{$data['Hora_Final']}'" : 'NULL') . ', `Fecha_inicion`=' . (($data['Fecha_inicion'] !== '' && $data['Fecha_inicion'] !== NULL) ? "'{$data['Fecha_inicion']}'" : 'NULL') . ', `Facilitador`=' . (($data['Facilitador'] !== '' && $data['Facilitador'] !== NULL) ? "'{$data['Facilitador']}'" : 'NULL') . ', `mapa`=' . (($data['mapa'] !== '' && $data['mapa'] !== NULL) ? "'{$data['mapa']}'" : 'NULL') . ', `mapa_link`=' . (($data['mapa_link'] !== '' && $data['mapa_link'] !== NULL) ? "'{$data['mapa_link']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"Cotrol_Acad_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: Cotrol_Acad_after_insert
	if(function_exists('Cotrol_Acad_after_insert')){
		$res = sql("select * from `Cotrol_Acad` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Cotrol_Acad_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Cotrol_Acad', $recID, getLoggedMemberID());

	return $recID;
}

function Cotrol_Acad_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Cotrol_Acad');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Cotrol_Acad' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Cotrol_Acad' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Cotrol_Acad_before_delete
	if(function_exists('Cotrol_Acad_before_delete')){
		$args=array();
		if(!Cotrol_Acad_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Cotrol_Acad` where `id`='$selected_id'", $eo);

	// hook: Cotrol_Acad_after_delete
	if(function_exists('Cotrol_Acad_after_delete')){
		$args=array();
		Cotrol_Acad_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Cotrol_Acad' and pkValue='$selected_id'", $eo);
}

function Cotrol_Acad_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Cotrol_Acad');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Cotrol_Acad' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Cotrol_Acad' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Codigo'] = makeSafe($_REQUEST['Codigo']);
		if($data['Codigo'] == empty_lookup_value){ $data['Codigo'] = ''; }
	$data['Seccion'] = makeSafe($_REQUEST['Seccion']);
		if($data['Seccion'] == empty_lookup_value){ $data['Seccion'] = ''; }
	$data['Nombre'] = makeSafe($_REQUEST['Nombre']);
		if($data['Nombre'] == empty_lookup_value){ $data['Nombre'] = ''; }
	$data['Aula'] = makeSafe($_REQUEST['Aula']);
		if($data['Aula'] == empty_lookup_value){ $data['Aula'] = ''; }
	$data['Dia'] = makeSafe($_REQUEST['Dia']);
		if($data['Dia'] == empty_lookup_value){ $data['Dia'] = ''; }
	$data['Hora_Inicio'] = makeSafe($_REQUEST['Hora_Inicio']);
		if($data['Hora_Inicio'] == empty_lookup_value){ $data['Hora_Inicio'] = ''; }
	$data['Hora_Final'] = makeSafe($_REQUEST['Hora_Final']);
		if($data['Hora_Final'] == empty_lookup_value){ $data['Hora_Final'] = ''; }
	$data['Fecha_inicion'] = makeSafe($_REQUEST['Fecha_inicion']);
		if($data['Fecha_inicion'] == empty_lookup_value){ $data['Fecha_inicion'] = ''; }
	$data['Facilitador'] = makeSafe($_REQUEST['Facilitador']);
		if($data['Facilitador'] == empty_lookup_value){ $data['Facilitador'] = ''; }
	$data['mapa'] = makeSafe($_REQUEST['mapa']);
		if($data['mapa'] == empty_lookup_value){ $data['mapa'] = ''; }
	$data['mapa_link'] = makeSafe($_REQUEST['mapa_link']);
		if($data['mapa_link'] == empty_lookup_value){ $data['mapa_link'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: Cotrol_Acad_before_update
	if(function_exists('Cotrol_Acad_before_update')){
		$args=array();
		if(!Cotrol_Acad_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `Cotrol_Acad` set       `Codigo`=' . (($data['Codigo'] !== '' && $data['Codigo'] !== NULL) ? "'{$data['Codigo']}'" : 'NULL') . ', `Seccion`=' . (($data['Seccion'] !== '' && $data['Seccion'] !== NULL) ? "'{$data['Seccion']}'" : 'NULL') . ', `Nombre`=' . (($data['Nombre'] !== '' && $data['Nombre'] !== NULL) ? "'{$data['Nombre']}'" : 'NULL') . ', `Aula`=' . (($data['Aula'] !== '' && $data['Aula'] !== NULL) ? "'{$data['Aula']}'" : 'NULL') . ', `Dia`=' . (($data['Dia'] !== '' && $data['Dia'] !== NULL) ? "'{$data['Dia']}'" : 'NULL') . ', `Hora_Inicio`=' . (($data['Hora_Inicio'] !== '' && $data['Hora_Inicio'] !== NULL) ? "'{$data['Hora_Inicio']}'" : 'NULL') . ', `Hora_Final`=' . (($data['Hora_Final'] !== '' && $data['Hora_Final'] !== NULL) ? "'{$data['Hora_Final']}'" : 'NULL') . ', `Fecha_inicion`=' . (($data['Fecha_inicion'] !== '' && $data['Fecha_inicion'] !== NULL) ? "'{$data['Fecha_inicion']}'" : 'NULL') . ', `Facilitador`=' . (($data['Facilitador'] !== '' && $data['Facilitador'] !== NULL) ? "'{$data['Facilitador']}'" : 'NULL') . ', `mapa`=' . (($data['mapa'] !== '' && $data['mapa'] !== NULL) ? "'{$data['mapa']}'" : 'NULL') . ', `mapa_link`=' . (($data['mapa_link'] !== '' && $data['mapa_link'] !== NULL) ? "'{$data['mapa_link']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="Cotrol_Acad_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Cotrol_Acad_after_update
	if(function_exists('Cotrol_Acad_after_update')){
		$res = sql("SELECT * FROM `Cotrol_Acad` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Cotrol_Acad_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='Cotrol_Acad' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function Cotrol_Acad_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Cotrol_Acad');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Cotrol_Acad' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Cotrol_Acad' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `Cotrol_Acad` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'Cotrol_Acad_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Cotrol_Acad_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Cotrol_Acad_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Control Acad&#233;mico', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Cotrol_Acad_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Cotrol_Acad_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Cotrol_Acad_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Codigo').replaceWith('<div class=\"form-control-static\" id=\"Codigo\">' + (jQuery('#Codigo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Seccion').replaceWith('<div class=\"form-control-static\" id=\"Seccion\">' + (jQuery('#Seccion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Nombre').replaceWith('<div class=\"form-control-static\" id=\"Nombre\">' + (jQuery('#Nombre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Aula').replaceWith('<div class=\"form-control-static\" id=\"Aula\">' + (jQuery('#Aula').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Dia').replaceWith('<div class=\"form-control-static\" id=\"Dia\">' + (jQuery('#Dia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Hora_Inicio').replaceWith('<div class=\"form-control-static\" id=\"Hora_Inicio\">' + (jQuery('#Hora_Inicio').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Hora_Final').replaceWith('<div class=\"form-control-static\" id=\"Hora_Final\">' + (jQuery('#Hora_Final').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Fecha_inicion').replaceWith('<div class=\"form-control-static\" id=\"Fecha_inicion\">' + (jQuery('#Fecha_inicion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Facilitador').replaceWith('<div class=\"form-control-static\" id=\"Facilitador\">' + (jQuery('#Facilitador').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#mapa').replaceWith('<div class=\"form-control-static\" id=\"mapa\">' + (jQuery('#mapa').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#mapa_link').replaceWith('<div class=\"form-control-static\" id=\"mapa_link\">' + (jQuery('#mapa_link').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Codigo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Seccion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nombre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Aula)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Dia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Hora_Inicio)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Hora_Final)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Fecha_inicion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Facilitador)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(mapa)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(mapa_link)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Codigo)%%>', safe_html($urow['Codigo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Codigo)%%>', html_attr($row['Codigo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Codigo)%%>', urlencode($urow['Codigo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Seccion)%%>', safe_html($urow['Seccion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Seccion)%%>', html_attr($row['Seccion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Seccion)%%>', urlencode($urow['Seccion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nombre)%%>', safe_html($urow['Nombre']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nombre)%%>', html_attr($row['Nombre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nombre)%%>', urlencode($urow['Nombre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Aula)%%>', safe_html($urow['Aula']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Aula)%%>', html_attr($row['Aula']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Aula)%%>', urlencode($urow['Aula']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Dia)%%>', safe_html($urow['Dia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Dia)%%>', html_attr($row['Dia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Dia)%%>', urlencode($urow['Dia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Hora_Inicio)%%>', safe_html($urow['Hora_Inicio']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Hora_Inicio)%%>', html_attr($row['Hora_Inicio']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hora_Inicio)%%>', urlencode($urow['Hora_Inicio']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Hora_Final)%%>', safe_html($urow['Hora_Final']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Hora_Final)%%>', html_attr($row['Hora_Final']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hora_Final)%%>', urlencode($urow['Hora_Final']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Fecha_inicion)%%>', safe_html($urow['Fecha_inicion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Fecha_inicion)%%>', html_attr($row['Fecha_inicion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_inicion)%%>', urlencode($urow['Fecha_inicion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Facilitador)%%>', safe_html($urow['Facilitador']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Facilitador)%%>', html_attr($row['Facilitador']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Facilitador)%%>', urlencode($urow['Facilitador']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(mapa)%%>', safe_html($urow['mapa']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mapa)%%>', html_attr($row['mapa']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mapa)%%>', urlencode($urow['mapa']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(mapa_link)%%>', safe_html($urow['mapa_link']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mapa_link)%%>', html_attr($row['mapa_link']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mapa_link)%%>', urlencode($urow['mapa_link']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Codigo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Codigo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Seccion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Seccion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nombre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nombre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Aula)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Aula)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Dia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Dia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Hora_Inicio)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hora_Inicio)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Hora_Final)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hora_Final)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_inicion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_inicion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Facilitador)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Facilitador)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(mapa)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mapa)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(mapa_link)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mapa_link)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Cotrol_Acad');
	if($selected_id){
		$jdata = get_joined_record('Cotrol_Acad', $selected_id);
		if($jdata === false) $jdata = get_defaults('Cotrol_Acad');
		$rdata = $row;
	}
	$templateCode .= loadView('Cotrol_Acad-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Cotrol_Acad_dv
	if(function_exists('Cotrol_Acad_dv')){
		$args=array();
		Cotrol_Acad_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>