<?php

// Data functions (insert, update, delete, form) for table inscripciones

// This script and data application were generated by AppGini 5.76
// Download AppGini for free from https://bigprof.com/appgini/download/

function inscripciones_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('inscripciones');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Codigo'] = makeSafe($_REQUEST['Codigo']);
		if($data['Codigo'] == empty_lookup_value){ $data['Codigo'] = ''; }
	$data['Seccion'] = makeSafe($_REQUEST['Seccion']);
		if($data['Seccion'] == empty_lookup_value){ $data['Seccion'] = ''; }
	$data['Periodo'] = makeSafe($_REQUEST['Periodo']);
		if($data['Periodo'] == empty_lookup_value){ $data['Periodo'] = ''; }
	$data['Matricula'] = makeSafe($_REQUEST['Matricula']);
		if($data['Matricula'] == empty_lookup_value){ $data['Matricula'] = ''; }

	// hook: inscripciones_before_insert
	if(function_exists('inscripciones_before_insert')){
		$args=array();
		if(!inscripciones_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `inscripciones` set       `Codigo`=' . (($data['Codigo'] !== '' && $data['Codigo'] !== NULL) ? "'{$data['Codigo']}'" : 'NULL') . ', `Seccion`=' . (($data['Seccion'] !== '' && $data['Seccion'] !== NULL) ? "'{$data['Seccion']}'" : 'NULL') . ', `Periodo`=' . (($data['Periodo'] !== '' && $data['Periodo'] !== NULL) ? "'{$data['Periodo']}'" : 'NULL') . ', `Matricula`=' . (($data['Matricula'] !== '' && $data['Matricula'] !== NULL) ? "'{$data['Matricula']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"inscripciones_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: inscripciones_after_insert
	if(function_exists('inscripciones_after_insert')){
		$res = sql("select * from `inscripciones` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!inscripciones_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('inscripciones', $recID, getLoggedMemberID());

	return $recID;
}

function inscripciones_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('inscripciones');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='inscripciones' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='inscripciones' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: inscripciones_before_delete
	if(function_exists('inscripciones_before_delete')){
		$args=array();
		if(!inscripciones_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `inscripciones` where `id`='$selected_id'", $eo);

	// hook: inscripciones_after_delete
	if(function_exists('inscripciones_after_delete')){
		$args=array();
		inscripciones_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='inscripciones' and pkValue='$selected_id'", $eo);
}

function inscripciones_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('inscripciones');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='inscripciones' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='inscripciones' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Codigo'] = makeSafe($_REQUEST['Codigo']);
		if($data['Codigo'] == empty_lookup_value){ $data['Codigo'] = ''; }
	$data['Seccion'] = makeSafe($_REQUEST['Seccion']);
		if($data['Seccion'] == empty_lookup_value){ $data['Seccion'] = ''; }
	$data['Periodo'] = makeSafe($_REQUEST['Periodo']);
		if($data['Periodo'] == empty_lookup_value){ $data['Periodo'] = ''; }
	$data['Matricula'] = makeSafe($_REQUEST['Matricula']);
		if($data['Matricula'] == empty_lookup_value){ $data['Matricula'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: inscripciones_before_update
	if(function_exists('inscripciones_before_update')){
		$args=array();
		if(!inscripciones_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `inscripciones` set       `Codigo`=' . (($data['Codigo'] !== '' && $data['Codigo'] !== NULL) ? "'{$data['Codigo']}'" : 'NULL') . ', `Seccion`=' . (($data['Seccion'] !== '' && $data['Seccion'] !== NULL) ? "'{$data['Seccion']}'" : 'NULL') . ', `Periodo`=' . (($data['Periodo'] !== '' && $data['Periodo'] !== NULL) ? "'{$data['Periodo']}'" : 'NULL') . ', `Matricula`=' . (($data['Matricula'] !== '' && $data['Matricula'] !== NULL) ? "'{$data['Matricula']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="inscripciones_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: inscripciones_after_update
	if(function_exists('inscripciones_after_update')){
		$res = sql("SELECT * FROM `inscripciones` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!inscripciones_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='inscripciones' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function inscripciones_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('inscripciones');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='inscripciones' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='inscripciones' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `inscripciones` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'inscripciones_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/inscripciones_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/inscripciones_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Inscripci&#243;n', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return inscripciones_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return inscripciones_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return inscripciones_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Codigo').replaceWith('<div class=\"form-control-static\" id=\"Codigo\">' + (jQuery('#Codigo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Seccion').replaceWith('<div class=\"form-control-static\" id=\"Seccion\">' + (jQuery('#Seccion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Periodo').replaceWith('<div class=\"form-control-static\" id=\"Periodo\">' + (jQuery('#Periodo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Matricula').replaceWith('<div class=\"form-control-static\" id=\"Matricula\">' + (jQuery('#Matricula').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Codigo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Seccion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Periodo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Matricula)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Codigo)%%>', safe_html($urow['Codigo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Codigo)%%>', html_attr($row['Codigo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Codigo)%%>', urlencode($urow['Codigo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Seccion)%%>', safe_html($urow['Seccion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Seccion)%%>', html_attr($row['Seccion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Seccion)%%>', urlencode($urow['Seccion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Periodo)%%>', safe_html($urow['Periodo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Periodo)%%>', html_attr($row['Periodo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Periodo)%%>', urlencode($urow['Periodo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Matricula)%%>', safe_html($urow['Matricula']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Matricula)%%>', html_attr($row['Matricula']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Matricula)%%>', urlencode($urow['Matricula']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Codigo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Codigo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Seccion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Seccion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Periodo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Periodo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Matricula)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Matricula)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('inscripciones');
	if($selected_id){
		$jdata = get_joined_record('inscripciones', $selected_id);
		if($jdata === false) $jdata = get_defaults('inscripciones');
		$rdata = $row;
	}
	$templateCode .= loadView('inscripciones-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: inscripciones_dv
	if(function_exists('inscripciones_dv')){
		$args=array();
		inscripciones_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>