<?php
// This script and data application were generated by AppGini 5.76
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/inscripciones.php");
	include("$currDir/inscripciones_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('inscripciones');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "inscripciones";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`inscripciones`.`id`" => "id",
		"`inscripciones`.`Codigo`" => "Codigo",
		"`inscripciones`.`Seccion`" => "Seccion",
		"`inscripciones`.`Periodo`" => "Periodo",
		"`inscripciones`.`Matricula`" => "Matricula"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`inscripciones`.`id`',
		2 => '`inscripciones`.`Codigo`',
		3 => '`inscripciones`.`Seccion`',
		4 => 4,
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`inscripciones`.`id`" => "id",
		"`inscripciones`.`Codigo`" => "Codigo",
		"`inscripciones`.`Seccion`" => "Seccion",
		"`inscripciones`.`Periodo`" => "Periodo",
		"`inscripciones`.`Matricula`" => "Matricula"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`inscripciones`.`id`" => "ID",
		"`inscripciones`.`Codigo`" => "C&#243;digo",
		"`inscripciones`.`Seccion`" => "Secci&#243;n",
		"`inscripciones`.`Periodo`" => "Per&#237;odo",
		"`inscripciones`.`Matricula`" => "Matricula"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`inscripciones`.`id`" => "id",
		"`inscripciones`.`Codigo`" => "Codigo",
		"`inscripciones`.`Seccion`" => "Seccion",
		"`inscripciones`.`Periodo`" => "Periodo",
		"`inscripciones`.`Matricula`" => "Matricula"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`inscripciones` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "inscripciones_view.php";
	$x->RedirectAfterInsert = "inscripciones_view.php?SelectedID=#ID#";
	$x->TableTitle = "Inscripci&#243;n";
	$x->TableIcon = "resources/table_icons/accept.png";
	$x->PrimaryKey = "`inscripciones`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("C&#243;digo", "Secci&#243;n", "Per&#237;odo", "Matricula");
	$x->ColFieldName = array('Codigo', 'Seccion', 'Periodo', 'Matricula');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/inscripciones_templateTV.html';
	$x->SelectedTemplate = 'templates/inscripciones_templateTVS.html';
	$x->TemplateDV = 'templates/inscripciones_templateDV.html';
	$x->TemplateDVP = 'templates/inscripciones_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `inscripciones`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='inscripciones' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `inscripciones`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='inscripciones' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`inscripciones`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: inscripciones_init
	$render=TRUE;
	if(function_exists('inscripciones_init')){
		$args=array();
		$render=inscripciones_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: inscripciones_header
	$headerCode='';
	if(function_exists('inscripciones_header')){
		$args=array();
		$headerCode=inscripciones_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: inscripciones_footer
	$footerCode='';
	if(function_exists('inscripciones_footer')){
		$args=array();
		$footerCode=inscripciones_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>